# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aed99bacaebac8f9ffb1f4c9bb0e2380"
name = "SyncBay"
application_url = "https://syncbay.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://syncbay.vercel.app/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "syncbay-dev.myshopify.com"
